name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.25.x' ]

    env:
      VERSION: test

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Ensure version.go exists
        run: make ensure-version

      - name: Vet
        run: go vet

      - name: Unit tests
        run: go test ./...

      - name: Prepare integration tests
        run: cd tests && go mod download

      - name: Integration tests
        run: cd tests && go test ./...
